# Generated by Django 5.1.4 on 2026-09-21 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('asset_type', models.CharField(default='image', max_length=20)),
                ('dimensions', models.CharField(default='1920 x 1080', max_length=50)),
                ('size_bytes', models.IntegerField(default=1500000)),
                ('folder', models.CharField(default='Campaign Assets', max_length=100)),
                ('tags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OAuthCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('twitter', 'X (Twitter)'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('pinterest', 'Pinterest')], max_length=30, unique=True)),
                ('client_id', models.CharField(help_text='Meta App ID / Google Client ID / Twitter Key', max_length=255)),
                ('client_secret', models.CharField(help_text='App Secret Key', max_length=255)),
                ('redirect_uri', models.CharField(default='http://127.0.0.1:8000/api/oauth/callback/', max_length=255)),
                ('developer_key', models.CharField(blank=True, help_text='YouTube API key / Bearer token', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_caption', models.TextField()),
                ('global_media_urls', models.JSONField(default=list)),
                ('platforms', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('partially_published', 'Partially Published'), ('failed', 'Failed')], default='draft', max_length=30)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_name', models.CharField(default='Likitha Sri', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('twitter', 'X (Twitter)'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('pinterest', 'Pinterest')], max_length=30)),
                ('account_name', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150)),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_connected', models.BooleanField(default=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('followers_count', models.IntegerField(default=0)),
                ('posts_published_count', models.IntegerField(default=0)),
                ('health', models.CharField(default='healthy', max_length=20)),
                ('last_synced', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('twitter', 'X (Twitter)'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('pinterest', 'Pinterest')], max_length=30)),
                ('caption', models.TextField(blank=True)),
                ('hashtags', models.JSONField(default=list)),
                ('custom_options', models.JSONField(default=dict)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='core.post')),
            ],
        ),
    ]
